### ISSUE TITLE
trapezio tem anemia

### ISSUE THREAD

**Issue by lia-lopes** [Material-PUCC/PythonProjects#2]
- no exercico 23 trapezio o height nunca funciona nao entendi rodei aqui ta duncionando nao tem erro na IDE como brinc

**Comment by nanaluvsu** [comment]
![image](https://github.com/Material-PUCC/PythonProjects/assets/102124577/93546d14-d704-43ca-b8eb-2744fdd2add4)

**Comment by lia-lopes** [comment]
![image](https://github.com/Material-PUCC/PythonProjects/assets/99834864/ff9fe390-5d16-480a-b9e8-4ceea90f1576)
